project_id = "sedqvrgoetvgclpoeorg"

[functions.regen-energy]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.explain-error]
verify_jwt = false